# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-07 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-image']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_category',
            new_name='category',
        ),
    ]
